version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: ex01-postgres
    environment:
      POSTGRES_USER: yumatsui
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    volumes:
      - ./volume:/var/lib/postgresql/data
    networks:
      - beaver-network

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: ex01-cloudbeaver
    ports:
      - "8080:8978"
    environment:
      CB_ADMIN_NAME: cbadmin
      CB_ADMIN_PASSWORD: CBadmin123
      CB_PUBLIC_URL: http://localhost:8080
    volumes:
      - ./cb_volumes:/opt/cloudbeaver/workspace
    networks:
      - beaver-network

networks:
  beaver-network:
    driver: bridge