version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: ex00
    environment:
      POSTGRES_USER: yumatsui
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    volumes:
      - ./volume:/var/lib/postgresql/data